title: Christopher Reed
theme: minima
author: Christopher Reed
email: reed.christopher17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog for all things ccreed717. Tiny houses, fake meat, socialism, and so much more.
  

# social links
github_username: ccreed717

show_excerpts: true # set to false to remove excerpts on the homepage
